version: "2"

run:
  timeout: 5m

linters:
  enable:
    - govet
    - staticcheck
    - errcheck
    - ineffassign
    - unused

formatters:
  enable:
    - gofmt

issues:
  exclude-use-default: false
